### ISSUE TITLE
Google Surveys

### ISSUE THREAD

**Issue by edvinlinden** [edvinlinden/killedby.tech#59]
**Product name:** Google Surveys
**Company:** Google
**Description:** Google Surveys was a service for business aimed at facilitating customized market research. It featured both a web interface with which to design the survey as well as the audience that takes the survey.
**Type of product:** Service
**Release date:** 2012-03-29
**Discontinued date:** 2022-11-01
**Source:** https://en.wikipedia.org/wiki/Google_Surveys

**Comment by MIfoodie** [comment]
@edvinlinden You might want to close this... it was added.

**Comment by edvinlinden** [comment]
Good catch @MIfoodie! 👍
