### ISSUE TITLE
Google Domains

### ISSUE THREAD

**Issue by mendykrauss** [edvinlinden/killedby.tech#67]
**Product name:** Google Domains
**Company:** Google
**Description:** Google Domains is a domain name registrar operated by Google. The service offers domain registration, DNS hosting, dynamic DNS, domain forwarding, and email forwarding. It provides native integration support for Google Cloud DNS and Google Workspace.
**Type of product:** Service
**Release date:** June 13, 2014
**Discontinued date:** June 15, 2023
**Source:** [https://support.google.com/domains/answer/13689670?sjid=8853709336626568186-NA]( https://support.google.com/domains/answer/13689670?sjid=8853709336626568186-NA)

**Comment by edvinlinden** [comment]
Thanks for the help @mendykrauss! I've added it to the site :)
