### ISSUE TITLE
Google Jamboard (APP)

### ISSUE THREAD

**Issue by FrankVan1982** [edvinlinden/killedby.tech#80]
**Product name:** Google Jamboard
**Company:** Google
**Description:** Google Jamboard was a web and native whiteboard app that offered a rich collaborative experience. It will be about 8 years old.
**Type of product:** App
**Release date:** 2018
**Discontinued date:** December 2024
**Source:** Google email that confirm the end-of-life of Google Jamboard app, and [https://en.wikipedia.org/wiki/Jamboard](https://en.wikipedia.org/wiki/Jamboard)

**Comment by edvinlinden** [comment]
Thanks for the contribution @FrankVan1982!
